### ISSUE TITLE
Error in alert message 

### ISSUE THREAD

**Issue by spro11** [JoomShaper/helix-ultimate#246]
On the page for creating an article in the front part of the site, there is an error in the layout of the message.
Close button does not work
![Снимок экрана 2021-11-17 155303](https://user-images.githubusercontent.com/52795457/142204319-10979063-bab5-4f2f-afbc-4ffd787b754b.jpg)

**Comment by mdamjadrana** [comment]
Can you share details.
Joomla version and others info?

**Comment by spro11** [comment]
### Steps to reproduce the issue

1. Add new menu item "Create Article"
2. Go to this item on frontend
3. Leave all fields blank and click on the save button

### System information (as much as possible)
Joomla! 3.10.5 / Helix Ultimate 2.0.6

Thanks!

**Comment by Savama51** [comment]
I confirm this problem with the close button of alert box, only under J3, not J4.
Simply go to a contact form in front-end, leave the fields empty and click the send button, the alert box appears in bottom-right of the page, close button doesn't work.

I found a similar problem with carousel bug (gallery.php), missing "-bs", since first HU 2 release :
data-dismiss="alert" -> data-bs-dismiss="alert" <- this works.

Hope fixes will follow soon.

**Comment by Savama51** [comment]
I've found a quick way to fix.
In /templates/shaper_helixultimate/js/bootstrap.bundle.min.js, line 6 col 7090 :
`[data-bs-dismiss="${s}"]`
Replaced by :
`[data-dismiss="${s}"]`
That's not really clean, but does the trick until a real fix !
